apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: front-end
          image: 410602862282.dkr.ecr.us-east-2.amazonaws.com/demo-poc:nodejs-image-8
          ports:
            - containerPort: 5000
